export const MESSAGE_TYPES = {
  OPEN_PDF_IN_VIEWER: "OPEN_PDF_IN_VIEWER",
  VIEWER_READY: "VIEWER_READY",
  VIEWER_STATE_CHANGED: "VIEWER_STATE_CHANGED",
  SIDE_PANEL_COMMAND: "SIDE_PANEL_COMMAND",
  LOAD_PDF_SOURCE: "LOAD_PDF_SOURCE",
  SAVE_PDF: "SAVE_PDF",
  EXPORT_PDF_DONE: "EXPORT_PDF_DONE",
  OPEN_SIDE_PANEL: "OPEN_SIDE_PANEL"
};

export const EDIT_MODES = {
  VIEW: "view",
  TEXT: "text",
  OBJECT: "object"
};
